// Client half of dsh-git-graph.
// Renders the commit DAG as an SVG "lane" graph (like VS Code Git Graph) next
// to a clickable commit list, with a detail pane showing message / files /
// diff. The panel opens either as a tab in dsh-better-sidebar (when present)
// or as a floating overlay toggled from the sidebar footer.
//
// GENERATED by scripts/build.mjs — do not edit the graph logic here; edit
// lib/graph.js (the single source of truth) and re-run the build.

window.__ModuleLoader__.load({
  id: 'dsh-git-graph',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })

    const React = require('react')
    const { createElement: h, useState, useEffect, useCallback, useRef, useMemo, Fragment } = React
    const { IconBranchOutline16, IconRefreshOutline16, IconSendOutline14, Tooltip } = require('@deepseek-ai/dsh-client-ui-primitives')
    const ReactDOM = require('react-dom')

    // Pure, framework-agnostic graph rendering for dsh-git-graph.
//
// This module is the SINGLE source of truth for the commit-graph layout and
// HTML/SVG generation. It is shared two ways:
//   - `lib/client.js` (the browser bundle) inlines it via `scripts/build.mjs`;
//   - `preview/preview.html` is generated from it by the same script.
// Nothing in here touches React, the DOM, or the DSH module loader — every
// function is a pure function that returns strings (HTML or SVG).

const ROW_H = 32
const COL_W = 16
const NODE_R = 4.5
const CORNER_R = 5
const PAD_X = 6

// Branch colors (assigned per branch name, high-distinction palette).
const BRANCH_COLORS = [
  '#3b82f6', '#22c55e', '#f59e0b', '#ef4444', '#a855f7',
  '#06b6d4', '#ec4899', '#84cc16', '#f97316', '#14b8a6',
]
const FALLBACK_COLOR = '#8b94a7'

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/** Branch names referenced by a commit's `%D` refs (tags and bare HEAD skipped). */
function branchNames(refs) {
  const names = []
  for (const r of refs) {
    if (!r || r === 'HEAD' || r.startsWith('tag: ')) continue
    let name = r
    if (r.startsWith('HEAD -> ')) name = r.slice(8).trim()
    name = name.replace(/^(origin|upstream|github)\//, '')
    if (name) names.push(name)
  }
  return names
}

/** Branch priority so main/develop/release/hotfix/feature get stable colors. */
function branchRank(name) {
  if (name === 'main' || name === 'master') return 0
  if (name === 'develop' || name === 'dev') return 1
  if (name.startsWith('release')) return 2
  if (name.startsWith('hotfix')) return 3
  if (name.startsWith('feature')) return 4
  return 5
}

/**
 * Stable color per branch: assign colors in priority order, then walk each
 * branch tip's first-parent chain, coloring commits; later branches stop at
 * already-colored commits. Returns Map<hash, color>.
 */
function branchColors(rows) {
  const byHash = new Map(rows.map(r => [r.hash, r]))
  // branch name -> tip hash (first commit carrying that name, newest first)
  const branchTip = new Map()
  rows.forEach(c => {
    for (const name of branchNames(c.refs)) {
      if (!branchTip.has(name)) branchTip.set(name, c.hash)
    }
  })
  const sortedNames = [...branchTip.keys()].sort((a, b) => {
    const ra = branchRank(a), rb = branchRank(b)
    return ra !== rb ? ra - rb : (a < b ? -1 : a > b ? 1 : 0)
  })
  const colorOfBranch = new Map()
  sortedNames.forEach((name, i) => { colorOfBranch.set(name, BRANCH_COLORS[i % BRANCH_COLORS.length]) })
  const colorOf = new Map()
  for (const name of sortedNames) {
    const color = colorOfBranch.get(name)
    let hash = branchTip.get(name)
    while (hash) {
      if (colorOf.has(hash)) break
      colorOf.set(hash, color)
      hash = byHash.get(hash)?.parents[0] ?? null
    }
  }
  rows.forEach(c => { if (!colorOf.has(c.hash)) colorOf.set(c.hash, FALLBACK_COLOR) })
  return colorOf
}

function relTime(iso) {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return ''
  const diff = Date.now() - d.getTime()
  const abs = Math.abs(diff)
  const rtf = new Intl.RelativeTimeFormat(undefined, { numeric: 'auto' })
  const units = [
    [31_536_000_000, 'year'], [2_592_000_000, 'month'], [86_400_000, 'day'],
    [3_600_000, 'hour'], [60_000, 'minute'], [1_000, 'second'],
  ]
  for (const [ms, unit] of units) {
    if (abs >= ms) return rtf.format(Math.round(-diff / ms), unit)
  }
  return 'just now'
}

function fmtDate(iso) {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

function refsHtml(refs) {
  if (!Array.isArray(refs) || refs.length === 0) return ''
  return refs.map(r => {
    if (r === 'HEAD') return '<span class="gg-ref gg-ref-head" data-kind="head">HEAD</span>'
    if (r.startsWith('HEAD ->')) {
      const branch = r.slice('HEAD ->'.length).trim()
      const head = '<span class="gg-ref gg-ref-head" data-kind="head">HEAD</span>'
      const b = branch ? `<span class="gg-ref gg-ref-current" data-kind="branch" data-ref="${esc(branch)}">${esc(branch)}</span>` : ''
      return head + b
    }
    if (r.startsWith('tag: ')) return `<span class="gg-ref gg-ref-tag" data-kind="tag" data-ref="${esc(r.slice(5))}">${esc(r.slice(5))}</span>`
    if (r.includes('/')) return `<span class="gg-ref gg-ref-remote" data-kind="remote" data-ref="${esc(r)}">${esc(r)}</span>`
    return `<span class="gg-ref gg-ref-branch" data-kind="branch" data-ref="${esc(r)}">${esc(r)}</span>`
  }).join('')
}

/** Highlight `backtick-quoted` spans in free text (returns escaped HTML). */
function inlineCodeHtml(text) {
  return String(text).split(/(`[^`]+`)/g).map(part => {
    if (part.length >= 2 && part.startsWith('`') && part.endsWith('`')) {
      return '<code class="gg-inline-code">' + esc(part.slice(1, -1)) + '</code>'
    }
    return esc(part)
  }).join('')
}

/** Classify one unified-diff line for syntax highlighting. */
function diffLineClass(line) {
  if (line.startsWith('diff --git')) return 'dl-file'
  if (line.startsWith('index ')) return 'dl-meta'
  if (line.startsWith('---')) return 'dl-file'
  if (line.startsWith('+++')) return 'dl-file'
  if (line.startsWith('@@')) return 'dl-hunk'
  if (line.startsWith('+')) return 'dl-add'
  if (line.startsWith('-')) return 'dl-del'
  if (line.startsWith('\\')) return 'dl-meta'
  return 'dl-ctx'
}

/** Render a unified diff as per-line `<div>` elements with highlighting. */
function diffHtml(diff) {
  return String(diff).replace(/\n+$/, '').split('\n').map(line => {
    const content = line.length > 0 ? esc(line) : '&nbsp;'
    return '<div class="dl ' + diffLineClass(line) + '">' + content + '</div>'
  }).join('')
}

/** Assign each commit a lane column (newest-first topo order). */
function layout(commits) {
  const column = new Map()
  const rowOf = new Map()
  const tips = []
  commits.forEach((c, i) => {
    rowOf.set(c.hash, i)
    let col = tips.indexOf(c.hash)
    if (col === -1) {
      col = tips.length
      tips.push(c.hash)
    }
    column.set(c.hash, col)
    c.parents.forEach((p, pi) => {
      if (pi === 0) {
        tips[col] = p
      } else {
        let pcol = tips.indexOf(p)
        if (pcol === -1) {
          pcol = tips.length
          tips.push(p)
        }
        tips[pcol] = p
      }
    })
  })
  let maxCol = 0
  const rows = commits.map(c => {
    const col = column.get(c.hash) ?? 0
    if (col > maxCol) maxCol = col
    return {
      ...c,
      col,
      parentCols: c.parents.map(p => column.get(p) ?? col),
    }
  })
  return { rows, maxCol, rowOf }
}

/**
 * Compute, for every row, which columns carry a vertical lane line in the
 * top half / bottom half of that row (Map: column → color), plus the elbows
 * (split/merge rounded corners) per row.
 */
function computeLanes(rows, rowOf, colorOf) {
  const n = rows.length
  const top = Array.from({ length: n }, () => new Map())
  const bottom = Array.from({ length: n }, () => new Map())
  const elbows = Array.from({ length: n }, () => [])
  rows.forEach((c, i) => {
    c.parents.forEach((p, pi) => {
      const rp = rowOf.get(p)
      if (rp === undefined) return
      const pc = c.parentCols[pi]
      if (pc === c.col) {
        // first parent, same column: straight lane down
        const color = colorOf.get(c.hash) ?? FALLBACK_COLOR
        bottom[i].set(pc, color)
        for (let r = i + 1; r < rp; r++) { top[r].set(pc, color); bottom[r].set(pc, color) }
        top[rp].set(pc, color)
      } else if (pi === 0) {
        // split: child lane continues UP from the parent. Vertical in the
        // child's column; the horizontal elbow sits in the PARENT's row and
        // turns right-then-up toward the child.
        const color = colorOf.get(c.hash) ?? FALLBACK_COLOR
        bottom[i].set(c.col, color)
        for (let r = i + 1; r < rp; r++) { top[r].set(c.col, color); bottom[r].set(c.col, color) }
        elbows[rp].push({ x1: pc, x2: c.col, color, up: true })
      } else {
        // merge: vertical continues down the merged parent's column; the
        // horizontal elbow sits in THIS row and turns right-then-down.
        const color = colorOf.get(p) ?? FALLBACK_COLOR
        for (let r = i + 1; r < rp; r++) { top[r].set(pc, color); bottom[r].set(pc, color) }
        top[rp].set(pc, color)
        elbows[i].push({ x1: c.col, x2: pc, color, up: false })
      }
    })
  })
  return { top, bottom, elbows }
}

/** One row's elbow: horizontal at the node's level, then rounded corner up or down. */
function elbowSlice(x1, x2, color, up) {
  const dir = x2 > x1 ? 1 : -1
  const y = ROW_H / 2
  const r = Math.max(2, Math.min(CORNER_R, Math.abs(x2 - x1) / 2))
  const endY = up ? 0 : ROW_H
  const qY = up ? y - r : y + r
  return `<path d="M ${x1 + dir * NODE_R} ${y} L ${x2 - dir * r} ${y} Q ${x2} ${y} ${x2} ${qY} L ${x2} ${endY}" fill="none" stroke="${color}" stroke-width="2" stroke-linecap="round"/>`
}

/** The graph slice (lane lines + node + elbows) for one commit row. */
function rowSlice(c, i, lanes, colorOf, maxCol, dirtyLink = null) {
  const w = (maxCol + 1) * COL_W + PAD_X * 2
  const cx = col => PAD_X + col * COL_W + COL_W / 2
  const parts = [`<svg class="gg-slice" width="${w}" height="${ROW_H}" viewBox="0 0 ${w} ${ROW_H}" style="position:static;width:${w}px;height:${ROW_H}px;display:block;flex:none;fill:none;stroke:none">`]
  if (dirtyLink) {
    parts.push(`<line x1="${cx(c.col)}" y1="0" x2="${cx(c.col)}" y2="${ROW_H / 2}" stroke="${dirtyLink}" stroke-width="2" stroke-dasharray="4 3" stroke-linecap="round" opacity="0.5"/>`)
  }
  for (let col = 0; col <= maxCol; col++) {
    const tc = lanes.top[i].get(col)
    const bc = lanes.bottom[i].get(col)
    if (tc) parts.push(`<line x1="${cx(col)}" y1="0" x2="${cx(col)}" y2="${ROW_H / 2}" stroke="${tc}" stroke-width="2" stroke-linecap="round"/>`)
    if (bc) parts.push(`<line x1="${cx(col)}" y1="${ROW_H / 2}" x2="${cx(col)}" y2="${ROW_H}" stroke="${bc}" stroke-width="2" stroke-linecap="round"/>`)
  }
  for (const el of lanes.elbows[i]) {
    parts.push(elbowSlice(cx(el.x1), cx(el.x2), el.color, el.up))
  }
  parts.push(`<circle cx="${cx(c.col)}" cy="${ROW_H / 2}" r="${NODE_R}" fill="${colorOf.get(c.hash) ?? FALLBACK_COLOR}" stroke="rgba(0,0,0,.35)" stroke-width="1"/>`)
  parts.push('</svg>')
  return parts.join('')
}

/** Top-of-graph "uncommitted changes" row: a dashed node + dashed link down to the first commit. */
function dirtyRowHtml(maxCol, firstCol, dirtyCount, color) {
  const w = (maxCol + 1) * COL_W + PAD_X * 2
  const cx = PAD_X + firstCol * COL_W + COL_W / 2
  const svg =
    `<svg class="gg-slice" width="${w}" height="${ROW_H}" viewBox="0 0 ${w} ${ROW_H}" style="position:static;width:${w}px;height:${ROW_H}px;display:block;flex:none;fill:none;stroke:none">` +
    `<line x1="${cx}" y1="${ROW_H / 2}" x2="${cx}" y2="${ROW_H}" stroke="${color}" stroke-width="2" stroke-dasharray="4 3" stroke-linecap="round" opacity="0.5"/>` +
    `<circle cx="${cx}" cy="${ROW_H / 2}" r="${NODE_R}" fill="${color}" opacity="0.5"/>` +
    `</svg>`
  return (
    `<div class="gg-row gg-row-dirty" style="height:${ROW_H}px">` +
    svg +
    `<span class="gg-subject">未提交的更改</span>` +
    `<span class="gg-meta">${dirtyCount} 个文件</span>` +
    `</div>`
  )
}

/** Full graph markup: one `.gg-row` per commit, each embedding its graph slice + text. */
function graphHtml(rows, maxCol, rowOf, colorOf, selectedHash, dirty = 0) {
  const lanes = computeLanes(rows, rowOf, colorOf)
  const dirtyColor = dirty > 0 && rows.length > 0 ? (colorOf.get(rows[0].hash) ?? FALLBACK_COLOR) : null
  const head = dirtyColor ? dirtyRowHtml(maxCol, rows[0].col, dirty, dirtyColor) : ''
  return head + rows.map((c, i) => {
    const refs = refsHtml(c.refs)
    const meta = [c.short ?? c.hash, c.author, relTime(c.date)].filter(Boolean).join(' · ')
    const sel = c.hash === selectedHash ? ' sel' : ''
    const link = i === 0 && dirtyColor ? dirtyColor : null
    return (
      `<div class="gg-row${sel}" data-hash="${esc(c.hash)}" style="height:${ROW_H}px">` +
      rowSlice(c, i, lanes, colorOf, maxCol, link) +
      refs +
      `<span class="gg-subject">${esc(c.subject || '(no subject)')}</span>` +
      `<span class="gg-meta">${esc(meta)}</span>` +
      `</div>`
    )
  }).join('')
}


    // ── 样式 ────────────────────────────────────────────────────────────────

    const CSS = [
      '.gg-panel{display:flex;flex-direction:column;height:100%;min-height:0;background:var(--dsw-alias-bg-base,#0f1115);color:var(--dsw-alias-label-primary,#e6e6e6);font-family:var(--dsh-font-ui,-apple-system,"PingFang SC","Segoe UI",sans-serif);font-size:13px}',
      '.gg-toolbar{display:flex;gap:8px;align-items:center;padding:8px 10px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.08));flex:none;flex-wrap:wrap}',
      '.gg-toolbar .gg-title{font-weight:600;margin-right:4px;display:flex;align-items:center;gap:6px}',
      '.gg-input{font:inherit;font-size:12px;color:var(--dsw-alias-label-primary,#e6e6e6);background:var(--dsw-alias-bg-layer-1,#1a1d24);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.1));border-radius:6px;padding:4px 8px;outline:none;min-width:0;box-sizing:border-box;height:28px;line-height:18px}',
      '.gg-input:focus{border-color:var(--dsw-alias-state-business-primary,#4c8dff)}',
      '.gg-input.gg-path{flex:1 1 160px;max-width:340px}',
      '.gg-input.gg-count{width:104px}',
      '.gg-input.gg-search{width:170px}',
      '.gg-input.gg-author{width:140px;max-width:160px}',
      '.gg-btn{font:inherit;font-size:12px;color:var(--dsw-alias-label-primary,#e6e6e6);background:var(--dsw-alias-button-elevated-fill,#262a33);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.1));border-radius:6px;padding:4px 10px;cursor:pointer;white-space:nowrap}',
      '.gg-btn:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#e6e6e6) 8%,transparent)}',
      '.gg-btn.primary{background:var(--dsw-alias-state-business-primary,#4c8dff);border-color:transparent;color:#fff}',
      '.gg-btn.primary:hover{background:color-mix(in srgb,var(--dsw-alias-state-business-primary,#4c8dff) 78%,#fff);border-color:transparent}',
      '.gg-btn.success{background:var(--dsw-alias-state-success-primary,#3fb950);border-color:transparent;color:#fff}',
      '.gg-btn.success:hover{background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3fb950) 78%,#fff);border-color:transparent}',
      '.gg-btn.gg-icon{padding:0;width:28px;height:28px;display:inline-flex;align-items:center;justify-content:center;flex:none}',
      '.gg-body{flex:1;display:flex;min-height:0}',
      '.gg-graph-col{flex:1;display:flex;flex-direction:column;min-width:0;min-height:0;overflow:auto;border-right:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.08))}',
      '.gg-detail{flex:1 1 40%;min-width:280px;max-width:46%;display:flex;flex-direction:column;min-height:0;overflow:auto;padding:12px 14px}',
      '.gg-graph-scroll{min-width:max-content}',
      '.gg-count-line{flex:none;padding:4px 12px;font-size:11px;color:var(--dsw-alias-label-tertiary,#8b94a7);border-bottom:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.06));position:sticky;top:0;background:var(--dsw-alias-bg-base,#0f1115);z-index:1}',
      '.gg-count-line.pushing{color:var(--dsw-alias-state-business-primary,#4c8dff);font-weight:600}',
      '.gg-btn:disabled{opacity:.5;cursor:default}',
      '.gg-slice{flex:none;display:block;position:static;width:auto;height:auto}',
      '.gg-panel svg,.gg-overlay svg,.gg-toggle svg{position:static;width:auto;height:auto;flex:none}',
      '.gg-row{display:flex;align-items:center;gap:6px;padding:0 10px 0 4px;cursor:pointer;white-space:nowrap;box-sizing:border-box;border-left:2px solid transparent;flex:none}',
      '.gg-row:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#e6e6e6) 5%,transparent)}',
      '.gg-row.sel{background:color-mix(in srgb,var(--dsw-alias-state-business-primary,#4c8dff) 14%,transparent);border-left-color:var(--dsw-alias-state-business-primary,#4c8dff)}',
      '.gg-row-dirty{cursor:default}',
      '.gg-row-dirty .gg-subject{color:var(--dsw-alias-label-tertiary,#8b94a7);font-style:italic}',
      '.gg-hash{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;color:var(--dsw-alias-label-tertiary,#8b94a7)}',
      '.gg-subject{overflow:hidden;text-overflow:ellipsis;color:var(--dsw-alias-label-primary,#e6e6e6)}',
      '.gg-meta{font-size:11px;color:var(--dsw-alias-label-tertiary,#8b94a7);flex:none}',
      '.gg-ref{display:inline-block;font-size:10px;line-height:16px;padding:0 6px;border-radius:8px;margin-right:4px;font-weight:600;vertical-align:middle}',
      '.gg-ref-head{background:#e5484d;color:#fff}',
      '.gg-ref-current{background:#8b5cf6;color:#fff}',
      '.gg-ref-branch{background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3fb950) 22%,transparent);color:var(--dsw-alias-state-success-primary,#3fb950)}',
      '.gg-ref-tag{background:color-mix(in srgb,#e3b341 22%,transparent);color:#e3b341}',
      '.gg-ref-remote{background:color-mix(in srgb,#79b8ff 18%,transparent);color:#79b8ff}',
      '.gg-status{flex:1;display:flex;align-items:center;justify-content:center;padding:24px;color:var(--dsw-alias-label-tertiary,#8b94a7);gap:8px;flex-wrap:wrap}',
      '.gg-status.err{color:var(--dsw-alias-state-error-primary,#f85149)}',
      '.gg-detail h3{margin:0 0 2px;font-size:14px;line-height:20px;font-weight:600;word-break:break-word}',
      '.gg-detail .gg-d-meta{font-size:12px;color:var(--dsw-alias-label-tertiary,#8b94a7);margin:2px 0 8px}',
      '.gg-d-body{white-space:pre-wrap;font-size:12.5px;line-height:18px;color:var(--dsw-alias-label-secondary,#c9d1d9);margin:0 0 12px}',
      '.gg-d-body .gg-inline-code{background:color-mix(in srgb,var(--dsw-alias-label-primary,#e6e6e6) 8%,transparent);color:var(--dsw-alias-label-primary,#e6e6e6);font-family:var(--ds-font-family-code,ui-monospace,SFMono-Regular,Menlo,monospace);font-size:12px;padding:1px 5px;border-radius:4px;border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.08))}',
      '.gg-d-files{margin:0 0 12px}',
      '.gg-d-files h4,.gg-d-diff h4{margin:0 0 4px;font-size:12px;color:var(--dsw-alias-label-secondary,#c9d1d9)}',
      '.gg-file{display:flex;gap:6px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:18px;color:var(--dsw-alias-label-secondary,#c9d1d9)}',
      '.gg-file .st{flex:none;width:26px;text-align:center;border-radius:3px;font-size:10px;line-height:16px;font-weight:700}',
      '.gg-file .st.A{background:rgba(46,160,67,.2);color:#3fb950}',
      '.gg-file .st.D{background:rgba(248,81,73,.2);color:#f85149}',
      '.gg-file .st.M,.gg-file .st.R{background:rgba(210,153,34,.18);color:#e3b341}',
      '.gg-diff{background:var(--dsw-alias-bg-layer-1,#1a1d24);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.08));border-radius:8px;overflow:auto;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:20px;max-height:420px}',
      '.gg-diff .dl{display:block;white-space:pre;padding:0 12px;min-height:20px;box-sizing:border-box}',
      '.gg-diff .dl-add{background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3fb950) 15%,transparent);color:var(--dsw-alias-state-success-primary,#3fb950)}',
      '.gg-diff .dl-del{background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#f85149) 15%,transparent);color:var(--dsw-alias-state-error-primary,#f85149)}',
      '.gg-diff .dl-hunk{background:color-mix(in srgb,var(--dsw-alias-state-business-primary,#4c8dff) 12%,transparent);color:var(--dsw-alias-state-business-primary,#79b8ff);font-weight:600}',
      '.gg-diff .dl-file{color:var(--dsw-alias-label-primary,#e6e6e6);font-weight:600}',
      '.gg-diff .dl-meta{color:var(--dsw-alias-label-tertiary,#8b94a7)}',
      '.gg-diff .dl-ctx{color:var(--dsw-alias-label-secondary,#c9d1d9)}',
      '.gg-empty{color:var(--dsw-alias-label-tertiary,#8b94a7);padding:12px 2px}',
      // footer toggle button
      '.gg-toggle{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:8px;border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.1));background:transparent;color:var(--dsw-alias-label-secondary,#c9d1d9);cursor:pointer}',
      '.gg-toggle:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#e6e6e6) 8%,transparent);color:var(--dsw-alias-label-primary,#e6e6e6)}',
      // floating overlay
      '.gg-overlay{position:fixed;inset:0;z-index:2147483000;background:rgba(0,0,0,.5);display:flex;align-items:stretch;justify-content:flex-end}',
      '.gg-overlay-panel{width:min(920px,94vw);height:100%;background:var(--dsw-alias-bg-base,#0f1115);box-shadow:-20px 0 60px rgba(0,0,0,.5);display:flex;flex-direction:column}',
      '.gg-overlay-head{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.08));flex:none}',
      '.gg-overlay-head .gg-title{font-weight:600}',
      '.gg-close{margin-left:auto;font:inherit;font-size:16px;line-height:1;color:var(--dsw-alias-label-secondary,#c9d1d9);background:transparent;border:none;cursor:pointer;padding:4px 8px;border-radius:6px}',
      '.gg-close:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#e6e6e6) 8%,transparent)}',
      // 写操作：右键菜单 / 确认弹窗 / toast
      '.gg-btn.danger{background:#b62324;border-color:transparent;color:#fff}',
      '.gg-btn.danger:hover{background:#d1242f}',
      '.gg-menu-backdrop{position:fixed;inset:0;z-index:2147483500}',
      '.gg-context-menu{position:fixed;z-index:2147483600;min-width:220px;max-width:320px;background:var(--dsw-alias-bg-layer-1,#1a1d24);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.1));border-radius:8px;padding:4px;box-shadow:0 10px 30px rgba(0,0,0,.5)}',
      '.gg-menu-item{display:block;width:100%;text-align:left;font:inherit;font-size:12px;color:var(--dsw-alias-label-primary,#e6e6e6);background:transparent;border:none;border-radius:5px;padding:6px 10px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
      '.gg-menu-item:hover{background:color-mix(in srgb,var(--dsw-alias-label-primary,#e6e6e6) 8%,transparent)}',
      '.gg-menu-item.danger{color:var(--dsw-alias-state-error-primary,#f85149)}',
      '.gg-menu-item.danger:hover{background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#f85149) 12%,transparent)}',
      '.gg-menu-sep{height:1px;margin:4px 6px;background:var(--dsw-alias-border-l1,rgba(255,255,255,.08))}',
      '.gg-modal-backdrop{position:fixed;inset:0;z-index:2147483500;background:rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center}',
      '.gg-modal{width:min(440px,92vw);background:var(--dsw-alias-bg-base,#0f1115);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.12));border-radius:12px;padding:16px;box-shadow:0 20px 60px rgba(0,0,0,.6);display:flex;flex-direction:column;gap:10px}',
      '.gg-modal-title{font-size:14px;font-weight:600}',
      '.gg-modal-cmd{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:var(--dsw-alias-label-secondary,#c9d1d9);background:var(--dsw-alias-bg-layer-1,#1a1d24);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.08));border-radius:6px;padding:6px 8px;word-break:break-all}',
      '.gg-modal-note{font-size:12px;color:var(--dsw-alias-label-tertiary,#8b94a7)}',
      '.gg-modal-input{width:100%}',
      '.gg-modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:2px}',
      '.gg-toast{position:fixed;bottom:24px;right:24px;z-index:2147483600;padding:10px 16px;border-radius:8px;font-size:13px;box-shadow:0 10px 30px rgba(0,0,0,.5)}',
      '.gg-toast.ok{background:color-mix(in srgb,var(--dsw-alias-state-success-primary,#3fb950) 20%,#0f1115);color:#3fb950;border:1px solid color-mix(in srgb,#3fb950 30%,transparent)}',
      '.gg-toast.err{background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#f85149) 20%,#0f1115);color:#f85149;border:1px solid color-mix(in srgb,#f85149 30%,transparent)}',
      '.gg-toast.warn{background:color-mix(in srgb,#e3b341 20%,#0f1115);color:#e3b341;border:1px solid color-mix(in srgb,#e3b341 30%,transparent)}',
    ].join('\n')

    if (typeof document !== 'undefined' && !document.querySelector('style[data-plugin-css="dsh-git-graph"]')) {
      const tag = document.createElement('style')
      tag.dataset.plugin = 'dsh-git-graph'
      tag.dataset.pluginCss = 'dsh-git-graph'
      tag.textContent = CSS
      document.head.appendChild(tag)
    }

    async function api(method, payload) {
      const res = await fetch(`/gitgraph/api/${method}`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(payload),
      })
      const parsed = await res.json().catch(() => null)
      if (!res.ok || parsed === null || parsed.ok !== true || parsed.value === undefined) {
        throw new Error(parsed?.error?.message ?? `HTTP ${res.status}`)
      }
      return parsed.value
    }

    // ── 主面板组件 ──────────────────────────────────────────────────────────

    function GitGraphPanel(props) {
      const { sessionId, initialCwd } = props
      const [state, setState] = useState({ status: 'loading', data: null, error: null })
      const [path, setPath] = useState(initialCwd || '')
      const [maxCount, setMaxCount] = useState(300)
      const [selected, setSelected] = useState(null)
      const [detail, setDetail] = useState({ status: 'idle', data: null, error: null })
      const [menu, setMenu] = useState(null)
      const [modal, setModal] = useState(null)
      const [toast, setToast] = useState(null)
      const [query, setQuery] = useState('')
      const [authorFilter, setAuthorFilter] = useState('')
      const [pushing, setPushing] = useState(false)
      const scrollRef = useRef(null)
      const maxCountRef = useRef(maxCount)
      useEffect(() => { maxCountRef.current = maxCount }, [maxCount])

      useEffect(() => {
        if (!toast) return
        const t = setTimeout(() => setToast(null), 4200)
        return () => clearTimeout(t)
      }, [toast])

      const load = useCallback(async (targetPath) => {
        setState(s => ({ ...s, status: 'loading', error: null }))
        try {
          const data = await api('graph', { sessionId, cwd: targetPath || undefined, maxCount: maxCountRef.current })
          setState({ status: 'ready', data, error: null })
          if (data && data.root) setPath(data.root)
          setSelected(null)
          setDetail({ status: 'idle', data: null, error: null })
        } catch (error) {
          setState({ status: 'error', data: null, error: error?.message ?? String(error) })
        }
      }, [sessionId])

      useEffect(() => {
        load(initialCwd)
      }, [load, initialCwd])

      const openCommit = useCallback(async (hash) => {
        setSelected(hash)
        setDetail({ status: 'loading', data: null, error: null })
        try {
          const d = await api('commit', { sessionId, cwd: path || undefined, hash })
          setDetail({ status: 'ready', data: d, error: null })
        } catch (error) {
          setDetail({ status: 'error', data: null, error: error?.message ?? String(error) })
        }
      }, [sessionId, path])

      const onRowClick = (e) => {
        const row = e.target.closest('.gg-row')
        if (row && row.dataset.hash) openCommit(row.dataset.hash)
      }

      // ── 写操作：执行 + 右键菜单 + 确认弹窗 ───────────────────────────────

      const doMutation = useCallback(async (method, payload, label) => {
        try {
          const res = await api(method, { sessionId, cwd: path || undefined, ...payload })
          if (res && res.conflict === true) {
            setToast({ type: 'warn', text: `${label} 产生冲突，请手动解决后刷新` })
          } else {
            setToast({ type: 'ok', text: `${label} 成功` })
          }
          load(path)
        } catch (error) {
          setToast({ type: 'err', text: `${label} 失败：${error?.message ?? error}` })
        }
      }, [sessionId, path, load])

      const doPush = useCallback(async () => {
        if (pushing) return
        setPushing(true)
        try {
          await api('push', { sessionId, cwd: path || undefined })
          setToast({ type: 'ok', text: '推送成功' })
          load(path)
        } catch (error) {
          setToast({ type: 'err', text: '推送失败：' + (error?.message ?? error) })
        } finally {
          setPushing(false)
        }
      }, [pushing, sessionId, path, load])

      const statusNote = async () => {
        try {
          const st = await api('status', { sessionId, cwd: path || undefined })
          if (st && st.dirty > 0) return `⚠ 工作区有 ${st.dirty} 个未提交变更，此操作可能受影响。`
        } catch { /* ignore */ }
        return ''
      }

      const openModal = async (builder) => { setModal(builder(await statusNote())) }

      const confirmCheckout = (ref, detach) => {
        openModal(note => ({
          title: detach ? '切换到提交（detached HEAD）' : `切换到分支 ${ref}`,
          command: `git checkout${detach ? ' --detach' : ''} ${ref}`,
          note, danger: false, inputs: [], confirmText: '切换',
          onSubmit: () => doMutation('checkout', { ref, detach }, `切换到 ${ref}`),
        }))
      }

      const promptCreateBranch = (hash) => {
        setModal({
          title: '新建分支', command: `git branch <name> ${hash.slice(0, 7)}`, note: '', danger: false,
          inputs: [{ key: 'name', label: '分支名', placeholder: 'feature/xxx', initial: '' }], confirmText: '创建',
          onSubmit: (values) => doMutation('createBranch', { name: values.name, from: hash }, `新建分支 ${values.name}`),
        })
      }

      const promptCreateTag = (hash) => {
        setModal({
          title: '打 tag', command: `git tag <name> ${hash.slice(0, 7)}`, note: '', danger: false,
          inputs: [{ key: 'name', label: 'Tag 名', placeholder: 'v1.0.0', initial: '' }], confirmText: '创建',
          onSubmit: (values) => doMutation('createTag', { name: values.name, hash }, `打 tag ${values.name}`),
        })
      }

      const promptRename = (name) => {
        setModal({
          title: `重命名分支 ${name}`, command: `git branch -m ${name} <new-name>`, note: '', danger: false,
          inputs: [{ key: 'name', label: '新分支名', placeholder: 'feature/new-name', initial: '' }], confirmText: '重命名',
          onSubmit: (values) => doMutation('renameBranch', { oldName: name, newName: values.name }, `重命名 ${name} → ${values.name}`),
        })
      }

      const confirmDeleteBranch = (name) => {
        setModal({
          title: `删除本地分支 ${name}`, command: `git branch -d ${name}`,
          note: '仅当分支已合并到上游时才删除。', danger: false, inputs: [], confirmText: '删除',
          onSubmit: () => doMutation('deleteBranch', { name, force: false }, `删除分支 ${name}`),
        })
      }

      const confirmDeleteRemote = (name) => {
        setModal({
          title: `删除远程分支 ${name}`, command: `git push origin --delete ${name}`,
          note: '将从 origin 删除远程分支，此操作不可逆。', danger: true,
          inputs: [{ key: 'confirm', label: `输入 ${name} 确认`, placeholder: name, initial: '' }], confirmText: '删除',
          onSubmit: (values) => {
            if (values.confirm !== name) { setToast({ type: 'err', text: '输入的分支名不匹配' }); throw new Error('mismatch') }
            return doMutation('deleteRemoteBranch', { name }, `删除远程分支 ${name}`)
          },
        })
      }

      const confirmDeleteTag = (name) => {
        setModal({
          title: `删除 tag ${name}`, command: `git tag -d ${name}`, note: '', danger: false, inputs: [], confirmText: '删除',
          onSubmit: () => doMutation('deleteTag', { name }, `删除 tag ${name}`),
        })
      }

      const confirmMerge = (ref) => {
        openModal(note => ({
          title: `合并 ${ref} 到当前分支`, command: `git merge ${ref}`, note, danger: false, inputs: [], confirmText: '合并',
          onSubmit: () => doMutation('merge', { ref }, `合并 ${ref}`),
        }))
      }

      const confirmCherryPick = (hash) => {
        openModal(note => ({
          title: 'cherry-pick', command: `git cherry-pick ${hash.slice(0, 7)}`, note, danger: false, inputs: [], confirmText: 'cherry-pick',
          onSubmit: () => doMutation('cherryPick', { hash }, `cherry-pick ${hash.slice(0, 7)}`),
        }))
      }

      const confirmRevert = (hash) => {
        openModal(note => ({
          title: 'revert', command: `git revert --no-edit ${hash.slice(0, 7)}`, note, danger: false, inputs: [], confirmText: 'revert',
          onSubmit: () => doMutation('revert', { hash }, `revert ${hash.slice(0, 7)}`),
        }))
      }

      const confirmReset = (hash, mode) => {
        const hard = mode === 'hard'
        const note = hard
          ? '⚠ --hard 会丢弃工作区与暂存区的所有未提交变更，不可恢复！'
          : (mode === 'soft' ? '保留工作区与暂存区，仅移动分支指针。' : '保留工作区，重置暂存区。')
        setModal({
          title: `reset 到 ${hash.slice(0, 7)}（--${mode}）`, command: `git reset --${mode} ${hash.slice(0, 7)}`,
          note, danger: hard,
          inputs: hard ? [{ key: 'confirm', label: '输入 RESET 确认', placeholder: 'RESET', initial: '' }] : [], confirmText: 'reset',
          onSubmit: (values) => {
            if (hard && values.confirm !== 'RESET') { setToast({ type: 'err', text: '请输入 RESET 确认' }); throw new Error('mismatch') }
            return doMutation('reset', { hash, mode }, `reset --${mode} ${hash.slice(0, 7)}`)
          },
        })
      }

      const onContextMenu = (e) => {
        const rowEl = e.target.closest('.gg-row')
        if (!rowEl) return
        const hash = rowEl.dataset.hash
        if (!hash) return
        e.preventDefault()
        const refEl = e.target.closest('.gg-ref')
        const items = []
        if (refEl && refEl.dataset.kind) {
          const kind = refEl.dataset.kind
          const name = refEl.dataset.ref || ''
          if (kind === 'branch' && name) {
            items.push({ label: `切换到 ${name}`, danger: false, onClick: () => confirmCheckout(name, false) })
            items.push({ label: `合并 ${name} 到当前分支`, danger: false, onClick: () => confirmMerge(name) })
            items.push({ sep: true })
            items.push({ label: `重命名 ${name}…`, danger: false, onClick: () => promptRename(name) })
            items.push({ label: `删除本地分支 ${name}`, danger: false, onClick: () => confirmDeleteBranch(name) })
            items.push({ label: `删除远程分支 ${name}`, danger: true, onClick: () => confirmDeleteRemote(name) })
          } else if (kind === 'tag' && name) {
            items.push({ label: `删除 tag ${name}`, danger: false, onClick: () => confirmDeleteTag(name) })
          }
        } else {
          items.push({ label: '切换到此提交（detached）', danger: false, onClick: () => confirmCheckout(hash, true) })
          items.push({ label: '新建分支…', danger: false, onClick: () => promptCreateBranch(hash) })
          items.push({ label: '打 tag…', danger: false, onClick: () => promptCreateTag(hash) })
          items.push({ sep: true })
          items.push({ label: 'cherry-pick', danger: false, onClick: () => confirmCherryPick(hash) })
          items.push({ label: 'revert', danger: false, onClick: () => confirmRevert(hash) })
          items.push({ label: 'reset（--soft）', danger: false, onClick: () => confirmReset(hash, 'soft') })
          items.push({ label: 'reset（--mixed）', danger: false, onClick: () => confirmReset(hash, 'mixed') })
          items.push({ label: 'reset（--hard）', danger: true, onClick: () => confirmReset(hash, 'hard') })
        }
        if (items.length === 0) return
        const x = Math.min(e.clientX, (typeof window !== 'undefined' ? window.innerWidth : 1000) - 260)
        const y = Math.min(e.clientY, (typeof window !== 'undefined' ? window.innerHeight : 800) - items.length * 30 - 16)
        setMenu({ x, y, items })
      }

      const authors = useMemo(() => {
        const seen = new Map()
        for (const c of state.data?.commits ?? []) {
          if (c.author && !seen.has(c.author)) seen.set(c.author, c.author)
        }
        return [...seen.keys()].sort((a, b) => a.localeCompare(b))
      }, [state.data])

      const filteredCommits = useMemo(() => {
        const commits = state.data?.commits ?? []
        const q = query.trim().toLowerCase()
        return commits.filter(c => {
          if (authorFilter && c.author !== authorFilter) return false
          if (!q) return true
          return (c.subject || '').toLowerCase().includes(q)
            || (c.hash || '').toLowerCase().includes(q)
            || (c.short || '').toLowerCase().includes(q)
            || (c.author || '').toLowerCase().includes(q)
            || (c.authorEmail || '').toLowerCase().includes(q)
        })
      }, [state.data, query, authorFilter])

      const visibleHashes = useMemo(() => filteredCommits.map(c => c.hash), [filteredCommits])

      const layoutData = useMemo(() => layout(filteredCommits), [filteredCommits])

      const graphMarkup = useMemo(() => {
        if (filteredCommits.length === 0) return ''
        const colorOf = branchColors(layoutData.rows)
        const dirtyCount = (query.trim() === '' && authorFilter === '') ? (state.data?.dirty ?? 0) : 0
        return graphHtml(layoutData.rows, layoutData.maxCol, layoutData.rowOf, colorOf, selected, dirtyCount)
      }, [layoutData, filteredCommits, selected, state.data, query, authorFilter])

      const onKeyDown = (e) => {
        if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
          e.preventDefault()
          if (visibleHashes.length === 0) return
          const idx = selected ? visibleHashes.indexOf(selected) : -1
          let next
          if (idx === -1) next = e.key === 'ArrowDown' ? 0 : visibleHashes.length - 1
          else if (e.key === 'ArrowDown') next = Math.min(idx + 1, visibleHashes.length - 1)
          else next = Math.max(idx - 1, 0)
          setSelected(visibleHashes[next])
          setDetail({ status: 'idle', data: null, error: null })
        } else if (e.key === 'Enter') {
          if (selected) openCommit(selected)
        } else if (e.key === 'Escape') {
          setSelected(null)
          setDetail({ status: 'idle', data: null, error: null })
        }
      }

      return h(Fragment, null, h('div', { className: 'gg-panel', tabIndex: 0, onKeyDown },
        h('div', { className: 'gg-toolbar' },
          h('span', { className: 'gg-title' },
            h(IconBranchOutline16, { size: 16 }),
            'Git Graph',
          ),
          h('input', {
            className: 'gg-input gg-path', value: path, readOnly: true,
            spellCheck: false, placeholder: 'repository path', title: '仓库路径',
          }),
          h('input', {
            className: 'gg-input gg-search', value: query,
            spellCheck: false, placeholder: '搜索提交 / hash / 作者', title: '搜索',
            onChange: e => setQuery(e.target.value),
          }),
          h('select', {
            className: 'gg-input gg-author',
            value: authorFilter,
            title: '按作者筛选',
            onChange: e => setAuthorFilter(e.target.value),
          },
            h('option', { value: '' }, '全部作者'),
            authors.map(a => h('option', { value: a, key: a }, a)),
          ),
          h('select', {
            className: 'gg-input gg-count',
            value: maxCount,
            title: '提交数量上限',
            onChange: e => setMaxCount(Number(e.target.value)),
          },
            h('option', { value: 0 }, '全部'),
            h('option', { value: 100 }, '最近 100'),
            h('option', { value: 300 }, '最近 300'),
            h('option', { value: 500 }, '最近 500'),
            h('option', { value: 1000 }, '最近 1000'),
            h('option', { value: 2000 }, '最近 2000'),
          ),
          h(Tooltip, { label: pushing ? '推送中' : '推送', side: 'bottom', delayMs: 400 },
            h('button', { className: 'gg-btn success gg-icon', 'aria-label': '推送', disabled: pushing, onClick: doPush },
              h(IconSendOutline14, { size: 14 }),
            ),
          ),
          h(Tooltip, { label: '刷新', side: 'bottom', delayMs: 400 },
            h('button', { className: 'gg-btn primary gg-icon', 'aria-label': '刷新', onClick: () => load(path) },
              h(IconRefreshOutline16, { size: 16 }),
            ),
          ),
        ),
        h('div', { className: 'gg-body' },
          h('div', { className: 'gg-graph-col' },
            state.status === 'loading' && h('div', { className: 'gg-status' }, 'Loading commit graph…'),
            state.status === 'error' && h('div', { className: 'gg-status err' }, 'Error: ' + state.error),
            state.status === 'ready' && state.data && !state.data.isRepo && h('div', { className: 'gg-status' }, 'Not a git repository. Enter a repository path above.'),
            state.status === 'ready' && state.data && state.data.isRepo && state.data.commits.length === 0 && h('div', { className: 'gg-status' }, 'No commits yet.'),
            state.status === 'ready' && state.data && state.data.isRepo && state.data.commits.length > 0 && h('div', { className: 'gg-count-line' + (pushing ? ' pushing' : '') },
              pushing
                ? '推送中…'
                : (filteredCommits.length === state.data.commits.length
                  ? `${state.data.commits.length} commits`
                  : `匹配 ${filteredCommits.length} / ${state.data.commits.length} commits`),
            ),
            state.status === 'ready' && state.data && state.data.isRepo && state.data.commits.length > 0 && h('div', {
              className: 'gg-graph-scroll',
              ref: scrollRef,
              onClick: onRowClick,
              onContextMenu: onContextMenu,
              dangerouslySetInnerHTML: { __html: graphMarkup },
            }),
          ),
          h('div', { className: 'gg-detail' },
            selected === null && h('div', { className: 'gg-empty' }, 'Select a commit to see its message, changed files, and diff.'),
            selected !== null && detail.status === 'idle' && h('div', { className: 'gg-empty' }, '按 Enter 查看此提交详情，↑/↓ 切换提交'),
            selected !== null && detail.status === 'loading' && h('div', { className: 'gg-status' }, 'Loading commit…'),
            selected !== null && detail.status === 'error' && h('div', { className: 'gg-status err' }, 'Error: ' + detail.error),
            selected !== null && detail.status === 'ready' && detail.data && h(Fragment, null,
              h('div', { dangerouslySetInnerHTML: { __html: '<h3>' + esc(detail.data.subject || '(no subject)') + '</h3>' } }),
              h('div', { className: 'gg-d-meta' },
                h('span', null, esc(detail.data.short) + ' · ' + esc(detail.data.author)),
                h('span', null, ' · ' + esc(fmtDate(detail.data.authorDate))),
                h('div', { dangerouslySetInnerHTML: { __html: refsHtml(detail.data.refs) } }),
              ),
              detail.data.body ? h('pre', { className: 'gg-d-body', dangerouslySetInnerHTML: { __html: inlineCodeHtml(detail.data.body) } }) : null,
              h('div', { className: 'gg-d-files' },
                h('h4', null, `Changed files (${detail.data.files.length})`),
                h('div', null, detail.data.files.map(f =>
                  h('div', { className: 'gg-file', key: f.path },
                    h('span', { className: 'st ' + f.status.charAt(0) }, f.status.charAt(0)),
                    h('span', null, esc(f.path)),
                  ),
                )),
              ),
              detail.data.stats ? h('div', { className: 'gg-d-meta' }, esc(detail.data.stats)) : null,
              h('div', { className: 'gg-d-diff' },
                h('h4', null, 'Diff'),
                detail.data.diff ? h('div', { className: 'gg-diff', dangerouslySetInnerHTML: { __html: diffHtml(detail.data.diff) } }) : h('div', { className: 'gg-empty' }, 'No diff available.'),
              ),
            ),
          ),
        ),
      ),
      ReactDOM.createPortal(
        h(Fragment, null,
          menu && h(Fragment, null,
            h('div', { className: 'gg-menu-backdrop', onClick: () => setMenu(null) }),
            h('div', { className: 'gg-context-menu', style: { left: menu.x, top: menu.y }, onClick: e => e.stopPropagation() },
              menu.items.map((item, i) => item.sep
                ? h('div', { className: 'gg-menu-sep', key: 'sep' + i })
                : h('button', { className: 'gg-menu-item' + (item.danger ? ' danger' : ''), key: i, onClick: () => { const fn = item.onClick; setMenu(null); fn() } }, item.label),
              ),
            ),
          ),
          modal && h(ConfirmModal, { modal, onClose: () => setModal(null) }),
          toast && h('div', { className: 'gg-toast ' + toast.type }, toast.text),
        ),
        document.body,
      ),
    )
  }

    // ── 确认弹窗 ────────────────────────────────────────────────────────────

    function ConfirmModal({ modal, onClose }) {
      const [values, setValues] = useState({})
      const [busy, setBusy] = useState(false)
      useEffect(() => {
        const init = {}
        const inputs = modal.inputs || []
        inputs.forEach(i => { init[i.key] = i.initial || '' })
        setValues(init)
        setBusy(false)
      }, [modal])
      const set = (key, val) => setValues(v => ({ ...v, [key]: val }))
      const submit = async () => {
        if (busy) return
        setBusy(true)
        try {
          await modal.onSubmit(values)
          onClose()
        } catch (e) {
          // 校验不通过：留在弹窗让用户重试，错误已通过 toast 提示
        } finally {
          setBusy(false)
        }
      }
      return h('div', { className: 'gg-modal-backdrop', onClick: onClose },
        h('div', { className: 'gg-modal', onClick: e => e.stopPropagation() },
          h('div', { className: 'gg-modal-title' }, modal.title),
          modal.command ? h('div', { className: 'gg-modal-cmd' }, modal.command) : null,
          modal.note ? h('div', { className: 'gg-modal-note' }, modal.note) : null,
          (modal.inputs || []).map(inp =>
            h('input', {
              key: inp.key, className: 'gg-input gg-modal-input',
              placeholder: inp.placeholder, value: values[inp.key] ?? '',
              autoFocus: true, spellCheck: false,
              onChange: e => set(inp.key, e.target.value),
              onKeyDown: e => { if (e.key === 'Enter') submit() },
            }),
          ),
          h('div', { className: 'gg-modal-actions' },
            h('button', { className: 'gg-btn', onClick: onClose, disabled: busy }, '取消'),
            h('button', { className: 'gg-btn primary' + (modal.danger ? ' danger' : ''), onClick: submit, disabled: busy }, busy ? '执行中…' : modal.confirmText),
          ),
        ),
      )
    }

    // ── 浮动覆盖层 ──────────────────────────────────────────────────────────

    let overlayRoot = null
    let overlayCleanup = null
    let appCtx = null

    function openOverlay(ctx) {
      const list = ctx.sessions.list.getSnapshot()
      const sessionId = list.current
      const cwd = sessionId ? list.byId?.[sessionId]?.cwd : undefined
      if (overlayRoot) closeOverlay()
      const host = document.createElement('div')
      host.className = 'gg-overlay-host'
      document.body.appendChild(host)
      const reactDom = require('react-dom/client')
      const root = reactDom.createRoot(host)
      overlayRoot = { host, root }
      const close = () => closeOverlay()
      root.render(
        h('div', { className: 'gg-overlay', onClick: e => { if (e.target === e.currentTarget) close() } },
          h('div', { className: 'gg-overlay-panel' },
            h('div', { className: 'gg-overlay-head' },
              h('span', { className: 'gg-title' },
                h(IconBranchOutline16, { size: 16 }),
                'Git Graph',
              ),
              h('button', { className: 'gg-close', onClick: close }, '×'),
            ),
            h(GitGraphPanel, { sessionId, initialCwd: cwd }),
          ),
        ),
      )
      overlayCleanup = () => { root.unmount(); host.remove(); overlayRoot = null; overlayCleanup = null }
    }

    function closeOverlay() {
      if (overlayCleanup) overlayCleanup()
    }

    function ToggleButton() {
      const onClick = () => {
        if (overlayRoot) closeOverlay()
        else if (appCtx) openOverlay(appCtx)
      }
      return h(Tooltip, { label: 'Git Graph', side: 'right', delayMs: 400 },
        h('button', {
          className: 'gg-toggle', 'aria-label': 'Git Graph', onClick,
        }, h(IconBranchOutline16, { size: 16 })),
      )
    }

    // ── 插件主体 ────────────────────────────────────────────────────────────

    const inject = ['slots', 'sessions']

    function apply(ctx) {
      appCtx = ctx

      // 1) better-sidebar tab (best-effort; sidebar provides the chrome).
      // better-sidebar's client may load after this plugin, so register both
      // immediately (already available) AND deferred via ctx.inject (arrives
      // later). A flag guards against double registration.
      let tabRegistered = false
      const registerTab = (betterSidebar) => {
        if (tabRegistered) return
        if (!betterSidebar || typeof betterSidebar.registerTab !== 'function') return
        tabRegistered = true
        const dispose = betterSidebar.registerTab({
          id: 'git-graph',
          title: 'Git Graph',
          icon: (size) => h(IconBranchOutline16, { size }),
          single: true,
          order: 60,
          component: (props) => h(GitGraphPanel, {
            sessionId: props.scope?.sessionId,
            initialCwd: props.scope?.cwd,
          }),
        })
        ctx.effect(() => dispose, 'dsh-git-graph: better-sidebar tab')
      }

      try {
        registerTab(ctx.get('betterSidebar'))
      } catch (error) {
        console.warn('[dsh-git-graph] better-sidebar tab lookup failed:', error)
      }

      try {
        if (typeof ctx.inject === 'function') {
          ctx.inject(['betterSidebar'], (sctx) => { registerTab(sctx.betterSidebar) })
        }
      } catch (error) {
        console.warn('[dsh-git-graph] better-sidebar deferred registration failed:', error)
      }

      // 2) footer toggle (always available, opens the floating overlay)
      try {
        const slots = ctx.slots
        if (slots && typeof slots.inject === 'function') {
          slots.inject('sidebar.footer.action', () => {
            const dispose = slots.register(
              { name: 'sidebar.footer.action', id: 'dsh-git-graph', order: 20, inject: () => ({}) },
              ToggleButton,
            )
            return () => dispose()
          })
        }
      } catch (error) {
        console.warn('[dsh-git-graph] footer toggle registration failed:', error)
      }
    }

    exports.apply = apply
    exports.inject = inject
    return module.exports
  },
})
